#!/usr/bin/env tsx
/**
 * WHOOP API Data Exploration Script
 *
 * First run:  opens browser for WHOOP OAuth, stores tokens in .env.local
 * Later runs: uses stored tokens, auto-refreshes if expired
 *
 * Usage: npm run whoop:explore
 * Output: whoop-data-dump.json (raw responses from all endpoints)
 */

import * as fs from 'node:fs';
import * as http from 'node:http';
import * as path from 'node:path';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';

const execAsync = promisify(exec);

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const ENV_FILE = path.join(process.cwd(), '.env.local');
const DUMP_FILE = path.join(process.cwd(), 'whoop-data-dump.json');
const API_BASE = 'https://api.prod.whoop.com/developer';
const AUTH_URL = 'https://api.prod.whoop.com/oauth/oauth2/auth';
const TOKEN_URL = 'https://api.prod.whoop.com/oauth/oauth2/token';
const OAUTH_SCOPES =
  'read:recovery read:cycles read:workout read:sleep read:profile read:body_measurement offline';

// ---------------------------------------------------------------------------
// .env.local helpers
// ---------------------------------------------------------------------------

function readEnv(): Record<string, string> {
  if (!fs.existsSync(ENV_FILE)) return {};
  const env: Record<string, string> = {};
  for (const line of fs.readFileSync(ENV_FILE, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    env[trimmed.slice(0, eqIdx).trim()] = trimmed.slice(eqIdx + 1).trim();
  }
  return env;
}

function upsertEnvKey(content: string, key: string, value: string): string {
  const lines = content.split('\n');
  const idx = lines.findIndex((l) => l.trim().startsWith(`${key}=`));
  if (idx >= 0) {
    lines[idx] = `${key}=${value}`;
    return lines.join('\n');
  }
  const sectionIdx = lines.findIndex((l) => l.includes('# WHOOP'));
  if (sectionIdx >= 0) {
    lines.splice(sectionIdx + 1, 0, `${key}=${value}`);
  } else {
    if (lines[lines.length - 1].trim() !== '') lines.push('');
    lines.push('# WHOOP — generated by whoop-explore.ts', `${key}=${value}`);
  }
  return lines.join('\n');
}

function writeEnvKeys(updates: Record<string, string>): void {
  let content = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, 'utf-8') : '';
  for (const [k, v] of Object.entries(updates)) content = upsertEnvKey(content, k, v);
  fs.writeFileSync(ENV_FILE, content);
}

// ---------------------------------------------------------------------------
// Types — mirrors the WHOOP v2 API response shapes
// ---------------------------------------------------------------------------

export interface WhoopTokens {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  token_type: string;
  scope: string;
}

export interface WhoopUserProfile {
  user_id: number;
  email: string;
  first_name: string;
  last_name: string;
}

export interface WhoopBodyMeasurement {
  height_meter: number;
  weight_kilogram: number;
  max_heart_rate: number;
}

export interface WhoopRecovery {
  cycle_id: number;
  sleep_id: string;
  user_id: number;
  created_at: string;
  updated_at: string;
  score_state: string;
  score: {
    user_calibrating: boolean;
    recovery_score: number;
    resting_heart_rate: number;
    hrv_rmssd_milli: number;
    spo2_percentage: number;
    skin_temp_celsius: number;
  } | null;
}

export interface WhoopCycle {
  id: number;
  user_id: number;
  created_at: string;
  updated_at: string;
  start: string;
  end: string;
  timezone_offset: string;
  score_state: string;
  score: {
    strain: number;
    kilojoule: number;
    average_heart_rate: number;
    max_heart_rate: number;
  } | null;
}

export interface WhoopWorkout {
  id: string;
  user_id: number;
  created_at: string;
  updated_at: string;
  start: string;
  end: string;
  timezone_offset: string;
  sport_id: number;
  sport_name: string;
  score_state: string;
  score: {
    strain: number;
    average_heart_rate: number;
    max_heart_rate: number;
    kilojoule: number;
    percent_recorded: number;
    distance_meter: number;
    altitude_gain_meter: number;
    altitude_change_meter: number;
    zone_durations: {
      zone_zero_milli: number;
      zone_one_milli: number;
      zone_two_milli: number;
      zone_three_milli: number;
      zone_four_milli: number;
      zone_five_milli: number;
    };
  } | null;
}

export interface WhoopSleep {
  id: string;
  cycle_id: number;
  user_id: number;
  created_at: string;
  updated_at: string;
  start: string;
  end: string;
  timezone_offset: string;
  nap: boolean;
  score_state: string;
  score: {
    stage_summary: {
      total_in_bed_time_milli: number;
      total_awake_time_milli: number;
      total_no_data_time_milli: number;
      total_light_sleep_time_milli: number;
      total_slow_wave_sleep_time_milli: number;
      total_rem_sleep_time_milli: number;
      sleep_cycle_count: number;
      disturbance_count: number;
    };
    sleep_needed: {
      baseline_milli: number;
      need_from_sleep_debt_milli: number;
      need_from_recent_strain_milli: number;
      need_from_recent_nap_milli: number;
    };
    respiratory_rate: number;
    sleep_performance_percentage: number;
    sleep_consistency_percentage: number;
    sleep_efficiency_percentage: number;
  } | null;
}

// ---------------------------------------------------------------------------
// OAuth helpers
// ---------------------------------------------------------------------------

async function openBrowser(url: string): Promise<void> {
  const cmd =
    process.platform === 'darwin'
      ? `open "${url}"`
      : process.platform === 'win32'
        ? `start "" "${url}"`
        : `xdg-open "${url}"`;
  try {
    await execAsync(cmd);
  } catch {
    // silently fall back — caller already printed the URL
  }
}

function waitForAuthCode(redirectUri: string): Promise<string> {
  const parsed = new URL(redirectUri);
  const port = parseInt(parsed.port || (parsed.protocol === 'https:' ? '443' : '80'), 10);
  const callbackPath = parsed.pathname;

  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      const reqUrl = new URL(req.url!, `http://localhost:${port}`);
      if (reqUrl.pathname !== callbackPath) {
        res.writeHead(404);
        res.end();
        return;
      }

      const code = reqUrl.searchParams.get('code');
      const error = reqUrl.searchParams.get('error');

      if (error || !code) {
        const msg = error ?? 'No authorization code in callback';
        res.writeHead(400, { 'Content-Type': 'text/html' });
        res.end(
          `<html><body style="font-family:system-ui;padding:2rem"><h2>Authorization failed</h2><p>${msg}</p><p>You can close this window.</p></body></html>`,
        );
        server.close();
        reject(new Error(`Authorization failed: ${msg}`));
        return;
      }

      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`
        <html><body style="font-family:system-ui;text-align:center;padding:2rem;background:#0a0a0a;color:#fff">
          <h2 style="color:#00ff87">WHOOP Authorization Successful!</h2>
          <p>You can close this window and return to the terminal.</p>
        </body></html>
      `);
      server.close();
      resolve(code);
    });

    server.listen(port, () =>
      console.log(`  Listening for OAuth callback on port ${port}…`),
    );
    server.on('error', reject);

    setTimeout(() => {
      server.close();
      reject(new Error('OAuth timeout: no callback received within 5 minutes'));
    }, 5 * 60 * 1000);
  });
}

async function exchangeCode(
  code: string,
  clientId: string,
  clientSecret: string,
  redirectUri: string,
): Promise<WhoopTokens> {
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: redirectUri,
      client_id: clientId,
      client_secret: clientSecret,
    }).toString(),
  });
  if (!res.ok) throw new Error(`Token exchange failed: ${res.status} ${await res.text()}`);
  return res.json() as Promise<WhoopTokens>;
}

async function refreshAccessToken(
  storedRefresh: string,
  clientId: string,
  clientSecret: string,
): Promise<WhoopTokens> {
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: storedRefresh,
      client_id: clientId,
      client_secret: clientSecret,
      scope: 'offline',
    }).toString(),
  });
  if (!res.ok) throw new Error(`Token refresh failed: ${res.status} ${await res.text()}`);
  return res.json() as Promise<WhoopTokens>;
}

function saveTokens(t: WhoopTokens): void {
  writeEnvKeys({
    WHOOP_ACCESS_TOKEN: t.access_token,
    WHOOP_REFRESH_TOKEN: t.refresh_token,
    WHOOP_TOKEN_EXPIRES_AT: String(Date.now() + t.expires_in * 1000),
  });
}

// ---------------------------------------------------------------------------
// API fetch helpers
// ---------------------------------------------------------------------------

async function whoopGet<T>(
  endpoint: string,
  accessToken: string,
  params?: Record<string, string>,
): Promise<T> {
  const url = new URL(`${API_BASE}${endpoint}`);
  if (params) {
    for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
  }
  const res = await fetch(url.toString(), {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`${endpoint}: ${res.status} ${await res.text()}`);
  return res.json() as Promise<T>;
}

interface PaginatedResponse<T> {
  records: T[];
  next_token?: string;
}

async function fetchCollection<T>(
  endpoint: string,
  accessToken: string,
  maxRecords = 25,
): Promise<T[]> {
  const records: T[] = [];
  let nextToken: string | undefined;

  do {
    const params: Record<string, string> = { limit: '25' };
    if (nextToken) params.nextToken = nextToken;
    const page = await whoopGet<PaginatedResponse<T>>(endpoint, accessToken, params);
    records.push(...page.records);
    nextToken = page.next_token;
  } while (nextToken && records.length < maxRecords);

  return records.slice(0, maxRecords);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const env = readEnv();
  const clientId = env.WHOOP_CLIENT_ID;
  const clientSecret = env.WHOOP_CLIENT_SECRET;
  const redirectUri = env.WHOOP_REDIRECT_URI;

  if (!clientId || !clientSecret || !redirectUri) {
    console.error(
      '\nMissing required environment variables in .env.local:\n' +
        '  WHOOP_CLIENT_ID\n  WHOOP_CLIENT_SECRET\n  WHOOP_REDIRECT_URI\n',
    );
    process.exit(1);
  }

  // --- Acquire access token ---
  let accessToken: string;

  const storedAccess = env.WHOOP_ACCESS_TOKEN;
  const storedRefresh = env.WHOOP_REFRESH_TOKEN;
  const expiresAt = env.WHOOP_TOKEN_EXPIRES_AT ? parseInt(env.WHOOP_TOKEN_EXPIRES_AT, 10) : 0;

  if (storedAccess && storedRefresh) {
    const isExpired = Date.now() >= expiresAt - 60_000;
    if (isExpired) {
      console.log('Access token expired — refreshing…');
      const tokens = await refreshAccessToken(storedRefresh, clientId, clientSecret);
      saveTokens(tokens);
      accessToken = tokens.access_token;
      console.log('Tokens refreshed and saved to .env.local\n');
    } else {
      const expiresInMin = Math.round((expiresAt - Date.now()) / 60_000);
      console.log(`Using stored access token (expires in ~${expiresInMin} min)\n`);
      accessToken = storedAccess;
    }
  } else {
    const authUrl = new URL(AUTH_URL);
    authUrl.searchParams.set('client_id', clientId);
    authUrl.searchParams.set('redirect_uri', redirectUri);
    authUrl.searchParams.set('response_type', 'code');
    authUrl.searchParams.set('scope', OAUTH_SCOPES);
    authUrl.searchParams.set('state', 'movu-whoop-explore');

    console.log('\nStarting WHOOP OAuth authorization…');
    console.log('Opening browser. If it does not open automatically, visit:\n');
    console.log(`  ${authUrl.toString()}\n`);

    await openBrowser(authUrl.toString());
    const code = await waitForAuthCode(redirectUri);

    console.log('\nAuthorization code received — exchanging for tokens…');
    const tokens = await exchangeCode(code, clientId, clientSecret, redirectUri);
    saveTokens(tokens);
    accessToken = tokens.access_token;
    console.log('Tokens saved to .env.local\n');
  }

  // --- Fetch all endpoints ---
  console.log('Fetching WHOOP data…\n');

  const dump: Record<string, unknown> = {};

  async function fetchAndRecord(label: string, fn: () => Promise<unknown>): Promise<void> {
    process.stdout.write(`  ${label.padEnd(20)}`);
    try {
      const data = await fn();
      dump[label] = data;
      if (Array.isArray(data)) {
        const keys = data.length > 0 ? Object.keys(data[0] as object).join(', ') : '(empty)';
        console.log(`${data.length} records  [${keys}]`);
      } else if (data && typeof data === 'object') {
        console.log(`keys: ${Object.keys(data as object).join(', ')}`);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.log(`FAILED — ${msg}`);
      dump[label] = { error: msg };
    }
  }

  await fetchAndRecord('user_profile', () =>
    whoopGet<WhoopUserProfile>('/v2/user/profile/basic', accessToken),
  );
  await fetchAndRecord('body_measurement', () =>
    whoopGet<WhoopBodyMeasurement>('/v2/user/measurement/body', accessToken),
  );
  await fetchAndRecord('recovery', () =>
    fetchCollection<WhoopRecovery>('/v2/recovery', accessToken, 25),
  );
  await fetchAndRecord('cycles', () =>
    fetchCollection<WhoopCycle>('/v2/cycle', accessToken, 25),
  );
  await fetchAndRecord('workouts', () =>
    fetchCollection<WhoopWorkout>('/v2/activity/workout', accessToken, 25),
  );
  await fetchAndRecord('sleep', () =>
    fetchCollection<WhoopSleep>('/v2/activity/sleep', accessToken, 25),
  );

  fs.writeFileSync(DUMP_FILE, JSON.stringify(dump, null, 2));

  console.log(`\nRaw responses written to ${DUMP_FILE}\n`);
  console.log('Summary');
  console.log('─'.repeat(50));
  for (const [label, data] of Object.entries(dump)) {
    const status =
      data && typeof data === 'object' && 'error' in (data as object)
        ? 'ERROR'
        : Array.isArray(data)
          ? `${data.length} records`
          : `${Object.keys(data as object).length} fields`;
    console.log(`  ${label.padEnd(20)} ${status}`);
  }
}

main().catch((err) => {
  console.error('\nFatal error:', err instanceof Error ? err.message : err);
  process.exit(1);
});
